version: "3"
services:
  # next
  next:
    build: ./next
    platform: linux/x86_64
    container_name: "next"
    ports:
      - "3000:3000"
    volumes:
      - ./next:/usr/src/app/next
    command: "npm run dev"

  # spring
  app:
    image: openjdk:11
    platform: linux/x86_64
    container_name: "app"
    restart: always
    tty: true
    ports:
      - "9090:8080"
    depends_on:
      - sql
    volumes:
      - ./app:/srv:cached
    working_dir: /srv

  # SQL
  sql:
    image: mariadb:10.7
    platform: linux/x86_64
    container_name: "mariadb"
    volumes:
      - ./mariadb/dbconf/:/docker-entrypoint-initdb.d
      - ./mariadb/dbconf/mysql.cnf:/etc/mysql/conf.d/my.cnf
      - ./mariadb/setting:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "qiish"
      MYSQL_USER: "mariadb"
      MYSQL_PASSWORD: "mariadb"
      TZ: "Asia/Tokyo"
